apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: n8n-mtls
  namespace: n8n
spec:
  mtls:
    mode: STRICT  # PERMISSIVE | STRICT
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: db-disable-mtls
  namespace: n8n
spec:
  selector:
    matchLabels:
      app: postgres
  mtls:
    mode: DISABLE

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: n8n
  namespace: n8n
spec:
  host: n8n
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL      # DISABLE |  ISTIO_MUTUAL | SIMPLE

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: db-no-mtls
  namespace: n8n
spec:
  host: postgres.n8n.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
