apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: n8n-mtls
  namespace: n8n
spec:
  mtls:
    mode: STRICT  # PERMISSIVE | STRICT
#---
#apiVersion: networking.istio.io/v1beta1
#kind: DestinationRule
#metadata:
#  name: n8n
#  namespace: n8n
#spec:
#  host: n8n
#  trafficPolicy:
#    tls:
#      mode: SIMPLE   # DISABLE |  ISTIO_MUTUAL | SIMPLE
